### ISSUE TITLE
Message when trying to scan  - unable to get local issuer certificate

### ISSUE THREAD

**Issue by LibbyYoung** [snyk/snyk-visual-studio-plugin#177]
i have run snyk auth -d and attached details 
[snykMsg.txt](https://github.com/snyk/snyk-visual-studio-plugin/files/8911292/snykMsg.txt)

Can anyone advise as this is very new to me.

**Comment by asaf92** [comment]
Hi @LibbyYoung !

It looks like this issue is not specific to the VS plugin, but rather an issue with the Snyk CLI in general.
This error is usually due to having self-signed certificate in your certificate chain. 

If you understand the implications, you can try to use the `--insecure` flag as explained [here](https://support.snyk.io/hc/en-us/articles/360002618657-Unable-to-get-Issuer-Certificates-Locally).

If you're using the VS plugin you can check the `Ignore Unknown CA` option in the settings to get the same effect.

Regards,
Asaf
